version: '3.8'

services:
  airflow:
    build:
      context: .
      dockerfile: Dockerfile
    image: custom-airflow:latest
    container_name: airflow
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE: utc
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW_UID: 50000
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./mediawiki_history_dumps:/opt/mediawiki_history_dumps
      - ./databases:/opt/databases
    ports:
      - "8080:8080"
    command: webserver
    depends_on:
      - airflow_init

  scheduler:
    image: custom-airflow:latest
    build:
      context: .
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW_UID: 50000
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./mediawiki_history_dumps:/opt/mediawiki_history_dumps
      - ./databases:/opt/databases
    command: scheduler
    depends_on:
      - airflow_init

  airflow_init:
    image: custom-airflow:latest
    build:
      context: .
    restart: on-failure
    volumes:
      - ./scripts:/opt/airflow/scripts
      - ./dags:/opt/airflow/dags
      - ./mediawiki_history_dumps:/opt/mediawiki_history_dumps
      - ./databases:/opt/databases
    entrypoint: /opt/airflow/scripts/entrypoint-init.sh
