receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  prometheus:
    endpoint: "prometheus:9090"  # Prometheus service name in Docker

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [prometheus]