{
 "title": "vital_signs",
 "description": "DASHBOARDS ",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "GENERAL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tasks started vs Tasks finished",
     "type": "piechart",
     "description": "How many tasks have been started and how many have been finished",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(ti_start{dag_id=\"vital_signs\"})",
       "legendFormat": "STARTED"
      },
      {
       "expr": "max(ti_finish{dag_id=\"vital_signs\"})",
       "legendFormat": "FINISHED"
      }
     ]
    },
    {
     "title": "Up",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      { "expr": "up", "legendFormat": "up" }
     ]
    }
   ]
  },
  {
   "title": "RESOURCES",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU and MEMORY usage",
     "type": "gauge",
     "description": "resources used by airflow",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(dag_id) (cpu_usage{dag_id=\"vital_signs\"})",
       "legendFormat": "CPU USAGE"
      },
      {
       "expr": "sum by(dag_id) (mem_usage{dag_id=\"vital_signs\"})",
       "legendFormat": "MEM USAGE"
      }
     ]
    }
   ]
  },
  {
   "title": "TASK DURATION",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "0.95 percetile ",
     "type": "timeseries",
     "description": "what's the task duration under which fall 95% of the tasks",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(task_duration_bucket{dag_id=\"vital_signs\"}[5m])))",
       "legendFormat": "P95"
      }
     ]
    },
    {
     "title": "Mean task duration",
     "type": "timeseries",
     "description": "mean task duration",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(task_duration_sum{dag_id=\"vital_signs\"}[5m]) / rate(task_duration_count{dag_id=\"vital_signs\"}[5m])",
       "legendFormat": "mean"
      }
     ]
    }
   ]
  }
 ]
}