receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889" # Prometheus service name in Docker
    namespace: "airflow"  

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [prometheus]