{
 "title": "vital_signs",
 "description": "DASHBOARDS ",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "task", "label": "Task", "query": { "query": "label_values(task_id)" } }
  ]
 },
 "panels": [
  { "title": "GENERAL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Tasks started vs Tasks finished",
   "type": "piechart",
   "description": "How many tasks have been started and how many have been finished",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ti_start{dag_id=\"vital_signs\"})",
     "legendFormat": "STARTED"
    },
    {
     "expr": "sum(ti_finish{dag_id=\"vital_signs\", state=\"success\"})",
     "legendFormat": "FINISHED/Success"
    },
    {
     "expr": "sum(ti_finish{dag_id=\"vital_signs\", state=\"failed\"})",
     "legendFormat": "FINISHED/Failed"
    }
   ]
  },
  {
   "title": "Up",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "up", "legendFormat": "up" }
   ]
  },
  { "title": "RESOURCES", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU and MEMORY usage",
   "type": "gauge",
   "description": "mean resource usage per task (inside the container)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(dag_id) (cpu_usage{dag_id=\"vital_signs\"})",
     "legendFormat": "CPU USAGE"
    },
    {
     "expr": "avg by(dag_id) (mem_usage{dag_id=\"vital_signs\"})",
     "legendFormat": "MEM USAGE"
    }
   ]
  },
  { "title": "TASK DURATION", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Istogramma con percentili (0.5, 0.9, 0.95)",
   "type": "timeseries",
   "description": "I percentili definiscono dei bucket che contengono rispettivamente il 50% dei tempi di esecuzione, il 90% e il 95%.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(task_duration_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(task_duration_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(task_duration_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean task duration",
   "type": "timeseries",
   "description": "mean task duration",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "task_duration_sum{dag_id=\"vital_signs\", task_id=\"$task\"} / task_duration_count{dag_id=\"vital_signs\", task_id=\"$task\"}",
     "legendFormat": "mean"
    }
   ]
  }
 ]
}